# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='users1',
        ),
    ]
